--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/usy4/AboutMe
build-by-default: true
branches:
- main
projects:
  AboutMe:
    path: ""
    icon: "AboutMe.png"
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.0.0
      - src: "CortexPE/Commando/Commando"
        branch: "PM4"
        version: ^3.0.0
...